-- create tables
create table lb_usuarios (
    id                             number generated by default on null as identity 
                                   constraint lb_usuarios_id_pk primary key,
    nick                           varchar2(30 char)
                                   constraint lb_usuarios_nick_unq unique not null,
    nombre                         varchar2(50 char) not null,
    apellido                       varchar2(50 char) not null
)
;

create table lb_permisos (
    id                             number generated by default on null as identity 
                                   constraint lb_permisos_id_pk primary key,
    descripcion                    varchar2(4000 char) not null
)
;

create table lb_roles (
    id                             number generated by default on null as identity 
                                   constraint lb_roles_id_pk primary key,
    permiso_id                     number
                                   constraint lb_roles_permiso_id_fk
                                   references lb_permisos on delete cascade,
    descripcion                    varchar2(100 char) not null
)
;

-- table index
create index lb_roles_i1 on lb_roles (permiso_id);

create table lb_bioquimicos (
    id                             number generated by default on null as identity 
                                   constraint lb_bioquimicos_id_pk primary key,
    nombre                         varchar2(100 char),
    apellido                       varchar2(100 char),
    ci                             varchar2(25 char)
                                   constraint lb_bioquimicos_ci_unq unique,
    reg_prof                       varchar2(30 char),
    direccion                      varchar2(255 char),
    cel                            varchar2(25 char),
    usuario_sistema_id             number
                                   constraint lb_bioquimico_usuario_siste_fk
                                   references lb_usuarios on delete cascade
)
;

-- table index
create index lb_bioquimicos_i1 on lb_bioquimicos (usuario_sistema_id);

create table lb_areas (
    id                             number generated by default on null as identity 
                                   constraint lb_areas_id_pk primary key,
    descripcion                    varchar2(100 char) not null
)
;

create table lb_grupos (
    id                             number generated by default on null as identity 
                                   constraint lb_grupos_id_pk primary key,
    area_id                        number
                                   constraint lb_grupos_area_id_fk
                                   references lb_areas on delete cascade,
    descripcion                    varchar2(100 char) not null
)
;

-- table index
create index lb_grupos_i1 on lb_grupos (area_id);

create table lb_pruebas (
    id                             number generated by default on null as identity 
                                   constraint lb_pruebas_id_pk primary key,
    grupo_id                       number
                                   constraint lb_pruebas_grupo_id_fk
                                   references lb_grupos on delete cascade,
    descripcion                    varchar2(100 char) not null
)
;

-- table index
create index lb_pruebas_i1 on lb_pruebas (grupo_id);


-- triggers
create or replace trigger lb_usuarios_biu
    before insert or update 
    on lb_usuarios
    for each row
begin
    :new.nick := upper(:new.nick);
    :new.nombre := upper(:new.nombre);
    :new.apellido := upper(:new.apellido);
end lb_usuarios_biu;
/

create or replace trigger lb_permisos_biu
    before insert or update 
    on lb_permisos
    for each row
begin
    :new.descripcion := upper(:new.descripcion);
end lb_permisos_biu;
/

create or replace trigger lb_bioquimicos_biu
    before insert or update 
    on lb_bioquimicos
    for each row
begin
    :new.nombre := upper(:new.nombre);
    :new.apellido := upper(:new.apellido);
    :new.direccion := upper(:new.direccion);
end lb_bioquimicos_biu;
/

create or replace trigger lb_areas_biu
    before insert or update 
    on lb_areas
    for each row
begin
    :new.descripcion := upper(:new.descripcion);
end lb_areas_biu;
/

create or replace trigger lb_grupos_biu
    before insert or update 
    on lb_grupos
    for each row
begin
    :new.descripcion := upper(:new.descripcion);
end lb_grupos_biu;
/

create or replace trigger lb_pruebas_biu
    before insert or update 
    on lb_pruebas
    for each row
begin
    :new.descripcion := upper(:new.descripcion);
end lb_pruebas_biu;
/

-- load data
